#!/bin/bash

# load variables from .env file
export $(cat .env | xargs)

# remove existing docker-compose file
rm -rf docker-compose.yaml

# create docker-compose file from template
envsubst < compose-template.yaml > docker-compose.yaml

# make docker-compose file read only
chmod -w docker-compose.yaml
